version: '3.8'
services:
  db:
    image: postgres:15
    container_name: maos_a_arte_db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: maos_a_arte
    ports:
      - "5432:5432"